
### Create Admin
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@admin.com",
  "password": "admin",
  "role": "ADMIN"
}

### Create Reader (precisa logar com o Admin)
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "Reader",
  "email": "reader@user.com",
  "password": "reader",
  "role": "READER"
}




### ----------------------------------

### Create Writer (precisa logar com o Admin)
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "Writer",
  "email": "writer@user.com",
  "password": "writer",
  "role": "WRITER",
  "permissions": [
    {
      "action": "read",
      "resource": "User"
    }
  ]
}

### List Users
GET http://localhost:3000/users
Authorization: {{tokenAdmin}}


### Get User By Id
GET http://localhost:3000/users/cm9b88gsb00029dxwv5910hww



### Login
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### Get Token UserAdmin
@tokenAdmin = {{adminLogin.response.body.access_token}}



### Login
# @name readerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "reader@user.com",
  "password": "reader"
}

### Get Token UserAdmin
@tokenReader = {{readerLogin.response.body.access_token}}





###--------------------------------

### Login Writer
# @name writerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "writer@user.com",
  "password": "writer"
}

### Get Token UserAdmin
@tokenWriter = {{writerLogin.response.body.access_token}}




### Create Post
POST http://localhost:3000/posts
Content-Type:  application/json
Authorization: Bearer {{tokenAdmin}}

{
  "title": "First Post",
  "content": "This is the content of my first post",
  "published": false
}

### List Posts
GET http://localhost:3000/posts
Authorization: Bearer {{tokenAdmin}}

### Get Post
GET http://localhost:3000/posts/cm9gak2k100019d2qzauz081t
Authorization: Bearer {{tokenReader}}


2h43min
